name: invigilator_app
description: A new Flutter project.


publish_to: 'none' 

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  image_picker: ^1.0.1
  shared_preferences: ^2.0.18
  image: ^4.1.3
  path_provider: ^2.1.2
  tflite_flutter: ^0.11.0
  google_mlkit_commons: ^0.7.1
  google_mlkit_face_detection: ^0.11.0
  package_info_plus: ^8.0.2
  flutter_svg: ^2.0.10+1
  get: ^4.6.5
  connectivity_plus: ^3.0.3
  dio: ^5.4.0
  camera: ^0.9.4+5
  sqflite: ^2.3.3+1


dependency_overrides:
  win32: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.0.0+1

flutter:

  uses-material-design: true
  generate: true

  
  assets:
    - assets/icons/
    - assets/images/
    - assets/trainned_model/

  

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic
    - family: HindSiliguri
      fonts:
        - asset: assets/fonts/HindSiliguri-Regular.ttf
          weight: 400
        - asset: assets/fonts/HindSiliguri-Medium.ttf
          weight: 500
        - asset: assets/fonts/HindSiliguri-Bold.ttf
          weight: 800
        - asset: assets/fonts/HindSiliguri-SemiBold.ttf
          weight: 600
  
  
  
