name: invigilator_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  image_picker: ^1.0.1
  shared_preferences: ^2.0.18
  image: ^4.1.3
  path_provider: ^2.1.2
  tflite_flutter: ^0.10.0
  google_mlkit_commons: ^0.7.1
  google_mlkit_face_detection: ^0.11.0
  connectivity_plus: ^3.0.3
  flutter_screenutil: ^5.6.1
  package_info_plus: ^8.0.2
  flutter_svg: ^1.1.6
  google_fonts: ^4.0.4
  get: ^4.6.5
  dio: ^5.4.3+1
  sqflite: ^2.3.3+1
  camera: ^0.9.4+5
  http: ^1.2.1
  win32: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  very_good_analysis: ^5.0.0+1

dependency_overrides:
  http: ^1.1.0

flutter:

  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/trainned_model/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
